# Site settings
title: 
header-img: img/home-bg.png
email: theresa.l.morelli@gmail.com
copyright_name: theresamorelli
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  theresamorelli
learn_profile: theresamorelli
email_username: theresa.l.morelli@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
